# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltrevenge_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.CharField(default='go sightseeing', max_length=255),
            preserve_default=False,
        ),
    ]
