# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20190718_1545'),
        ('beltrevenge_app', '0002_trip_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trips',
            field=models.ManyToManyField(related_name='tourists', to='login_app.User'),
        ),
    ]
