# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-18 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='conf_pword',
            new_name='conf_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pword',
            new_name='password',
        ),
    ]
